module.exports = {
  docs: [
    {
      type: "doc",
      id: "index",
    },
    //todo How to start нет (папка tutorial, они сильно устрели)
    {
      type: "category",
      label: "Widgets",
      // collapsed: false,
      items: [
        //Calendar
        {
          type: "category",
          label: "Calendar",
          collapsed: true,
          items: [
            "calendar/index",
            {
              type: "category",
              label: "API",
              items: [
                "calendar/api/api_overview",

                {
                  type: "category",
                  label: "Methods",
                  items: [
                    "calendar/api/calendar_clear_method",
                    "calendar/api/calendar_destructor_method",
                    "calendar/api/calendar_getcurrentmode_method",
                    "calendar/api/calendar_getvalue_method",
                    "calendar/api/calendar_link_method",
                    "calendar/api/calendar_paint_method",
                    "calendar/api/calendar_setvalue_method",
                    "calendar/api/calendar_showdate_method",
                  ],
                },
                {
                  type: "category",
                  label: "Events",
                  items: [
                    "calendar/api/calendar_beforechange_event",
                    "calendar/api/calendar_cancelclick_event",
                    "calendar/api/calendar_change_event",
                    "calendar/api/calendar_datehover_event",
                    "calendar/api/calendar_datemouseover_event",
                    "calendar/api/calendar_modechange_event",
                    "calendar/api/calendar_monthselected_event",
                    "calendar/api/calendar_yearselected_event",
                  ],
                },
                {
                  type: "category",
                  label: "Properties",
                  items: [
                    "calendar/api/calendar_block_config",
                    "calendar/api/calendar_css_config",
                    "calendar/api/calendar_date_config",
                    "calendar/api/calendar_dateformat_config",
                    "calendar/api/calendar_disableddates_config",
                    "calendar/api/calendar_mark_config",
                    "calendar/api/calendar_mode_config",
                    "calendar/api/calendar_range_config",
                    "calendar/api/calendar_thismonthonly_config",
                    "calendar/api/calendar_timeformat_config",
                    "calendar/api/calendar_timepicker_config",
                    "calendar/api/calendar_value_config",
                    "calendar/api/calendar_view_config",
                    "calendar/api/calendar_weeknumbers_config",
                    "calendar/api/calendar_weekstart_config",
                    "calendar/api/calendar_width_config",
                  ],
                },
              ],
            },
            "calendar/how_to_start",
            "calendar/configuring",
            "calendar/localizing_calendar",
            "calendar/operating_calendar",
            "calendar/datepicker",
            // "calendar/api",
            "calendar/customization",
            "calendar/handling_events",
            "calendar/migration",
          ],
        },
        // end Calendar

        //Calendar2
        {
          type: "category",
          label: "Calendar2",
          collapsed: true,
          items: [
            "calendar2/index",
            {
              type: "category",
              label: "API",
              items: [
                "calendar/api/api_overview",

                {
                  type: "category",
                  label: "Methods",
                  items: [
                    "calendar/api/calendar_link_method",
                    "calendar/api/calendar_clear_method",
                    "calendar/api/calendar_paint_method",
                    "calendar/api/calendar_getcurrentmode_method",
                    "calendar/api/calendar_getvalue_method",
                    "calendar/api/calendar_setvalue_method",
                    "calendar/api/calendar_showdate_method",
                    "calendar/api/calendar_destructor_method",
                  ],
                },
                {
                  type: "category",
                  label: "Events",
                  items: [
                    "calendar/api/calendar_change_event",
                    "calendar/api/calendar_datehover_event",
                    "calendar/api/calendar_cancelclick_event",
                    "calendar/api/calendar_modechange_event",
                    "calendar/api/calendar_yearselected_event",
                    "calendar/api/calendar_monthselected_event",
                    "calendar/api/calendar_datemouseover_event",
                    "calendar/api/calendar_beforechange_event",
                  ],
                },
                {
                  type: "category",
                  label: "Properties",
                  items: [
                    "calendar/api/calendar_date_config",
                    "calendar/api/calendar_thismonthonly_config",
                    "calendar/api/calendar_disableddates_config",
                    "calendar/api/calendar_weeknumbers_config",
                    "calendar/api/calendar_dateformat_config",
                    "calendar/api/calendar_timepicker_config",
                    "calendar/api/calendar_timeformat_config",
                    "calendar/api/calendar_block_config",
                    "calendar/api/calendar_value_config",
                    "calendar/api/calendar_view_config",
                    "calendar/api/calendar_weekstart_config",
                    "calendar/api/calendar_css_config",
                    "calendar/api/calendar_mode_config",
                    "calendar/api/calendar_mark_config",
                    "calendar/api/calendar_range_config",
                    "calendar/api/calendar_width_config",
                  ],
                },
              ],
            },
            "calendar2/how_to_start",
            "calendar2/configuring",
            "calendar2/localizing_calendar",
            "calendar2/operating_calendar",
            "calendar2/datepicker",
            // "calendar/api",
            "calendar2/customization",
            "calendar2/handling_events",
            "calendar2/migration",
          ],
        },
        // end Calendar2

        //Chart
        {
          type: "category",
          label: "Chart",
          items: [
            "chart/index",
            {
              type: "category",
              label: "API",
              collapsed: true,
              items: [
                "calendar/api/api_overview", //todo 
                {
                  type: "category",
                  label: "Methods",
                  collapsed: true,
                  items: [
                    "chart/api/chart_getseries_method",
                    "chart/api/chart_eachseries_method",
                    "chart/api/chart_destructor_method",
                    "chart/api/chart_paint_method",
                    "chart/api/chart_setconfig_method",
                  ],
                },
                {
                  type: "category",
                  label: "Events",
                  collapsed: true,
                  items: [
                    "chart/api/chart_toggleseries_event",
                    "chart/api/chart_serieclick_event",
                    "chart/api/chart_resize_event",
                  ],
                },
                {
                  type: "category",
                  label: "Properties",
                  collapsed: true,
                  items: [
                    "chart/api/chart_css_config",
                    "chart/api/chart_series_config",
                    "chart/api/chart_type_config",
                    "chart/api/chart_maxpoints_config",
                    "chart/api/chart_scales_config",
                    "chart/api/chart_legend_config",
                  ],
                },
              ],
            },
            "chart/charts_overview",
            "chart/initialization",
            "chart/configuration_properties",
            "chart/data_loading",
            "chart/usage",
            "chart/customization",
            "chart/events",
            // "chart/migration",
          ],
        },
        // end Chart

        //Colorpicker
        {
          type: "category",
          label: "Colorpicker",
          items: [
            "colorpicker/index",
            {
              type: "category",
              label: "API",
              items: [
                "colorpicker/api/api_overview", //todo
                {
                  type: "category",
                  label: "Methods",
                  items: [
                    "colorpicker/api/colorpicker_clear_method",
                    "colorpicker/api/colorpicker_destructor_method",
                    "colorpicker/api/colorpicker_focusvalue_method",
                    "colorpicker/api/colorpicker_getcurrentmode_method",
                    "colorpicker/api/colorpicker_getcustomcolors_method",
                    "colorpicker/api/colorpicker_getvalue_method",
                    "colorpicker/api/colorpicker_getview_method",
                    "colorpicker/api/colorpicker_paint_method",
                    "colorpicker/api/colorpicker_setcurrentmode_method",
                    "colorpicker/api/colorpicker_setcustomcolors_method",
                    "colorpicker/api/colorpicker_setfocus_method",
                    "colorpicker/api/colorpicker_setvalue_method",
                    "colorpicker/api/colorpicker_setview_method",
                  ],
                },
                {
                  type: "category",
                  label: "Events",
                  items: [
                    "colorpicker/api/colorpicker_apply_event",
                    "colorpicker/api/colorpicker_cancelclick_event",
                    "colorpicker/api/colorpicker_change_event",
                    "colorpicker/api/colorpicker_colorchange_event",
                    "colorpicker/api/colorpicker_modechange_event",
                    "colorpicker/api/colorpicker_selectclick_event",
                    "colorpicker/api/colorpicker_viewchange_event",
                  ],
                },
                {
                  type: "category",
                  label: "Properties",
                  items: [
                    "colorpicker/api/colorpicker_css_config",
                    "colorpicker/api/colorpicker_customcolors_config",
                    "colorpicker/api/colorpicker_grayshades_config",
                    "colorpicker/api/colorpicker_mode_config",
                    "colorpicker/api/colorpicker_palette_config",
                    "colorpicker/api/colorpicker_paletteonly_config",
                    "colorpicker/api/colorpicker_pickeronly_config",
                    "colorpicker/api/colorpicker_width_config",
                  ],
                },
              ],
            },
            "colorpicker/how_to_start",
            "colorpicker/configuration",
            "colorpicker/localizing_colorpicker",
            "colorpicker/manipulating_colorpicker",
            "colorpicker/customization",
            "colorpicker/handling_events",
            "colorpicker/migration",
          ],
        },
        // end ColorPicker

        //Combobox
        {
          type: "category",
          label: "Combobox",
          items: [
            "combobox/index",
            {
              type: "category",
              label: "API",
              items: [
                // "calendar/api/api_overview", //todo
                {
                  type: "category",
                  label: "Methods",
                  items: [
                    "combobox/api/combobox_clear_method",
                    "combobox/api/combobox_disable_method",
                    "combobox/api/combobox_enable_method",
                    "combobox/api/combobox_getvalue_method",
                    "combobox/api/combobox_isdisabled_method",
                    "combobox/api/combobox_paint_method",
                    "combobox/api/combobox_setstate_method",
                    "combobox/api/combobox_setvalue_method",
                  ],
                },
                {
                  type: "category",
                  label: "Events",
                  collapsed: true,
                  items: [
                    "combobox/api/combobox_afterclose_event",
                    "combobox/api/combobox_beforeclose_event",
                    "combobox/api/combobox_close_event",
                    "combobox/api/combobox_destructor_method",
                    "combobox/api/combobox_input_event",
                    "combobox/api/combobox_open_event",
                  ],
                },
                {
                  type: "category",
                  label: "Properties",
                  items: [
                    "combobox/api/combobox_cellheight_config",
                    "combobox/api/combobox_css_config",
                    "combobox/api/combobox_data_config",
                    "combobox/api/combobox_disabled_config",
                    "combobox/api/combobox_filter_config",
                    "combobox/api/combobox_help_config",
                    "combobox/api/combobox_helpmessage_config",
                    "combobox/api/combobox_hiddenlabel_config",
                    "combobox/api/combobox_itemheight_config",
                    "combobox/api/combobox_itemscount_config",
                    "combobox/api/combobox_label_config",
                    "combobox/api/combobox_labelinline_config",
                    "combobox/api/combobox_labelposition_config",
                    "combobox/api/combobox_labelwidth_config",
                    "combobox/api/combobox_listheight_config",
                    "combobox/api/combobox_multiselection_config",
                    "combobox/api/combobox_placeholder_config",
                    "combobox/api/combobox_readonly_config",
                    "combobox/api/combobox_required_config",
                    "combobox/api/combobox_selectallbutton_config",
                    "combobox/api/combobox_showitemscount_config",
                    "combobox/api/combobox_template_config",
                    "combobox/api/combobox_value_config",
                    "combobox/api/combobox_virtual_config",
                  ],
                },
              ],
            },
            "combobox/how_to_start",
            "combobox/configuration",
            "combobox/localization",
            "combobox/adding_options",
            "combobox/work_with_combo",
            "combobox/customization",
            "combobox/handling_events",
            "combobox/migration",
          ],
        },
        // end Combobox

        //Dataview
        {
          type: "category",
          label: "Dataview",
          items: [
            "dataview/index",
            {
              type: "category",
              label: "API",
              items: [
                // "calendar/api/api_overview", //todo
                {
                  type: "category",
                  label: "Methods",
                  items: [
                    "dataview/api/dataview_destructor_method",
                    "dataview/api/dataview_disableselection_method",
                    "dataview/api/dataview_edit_method",
                    "dataview/api/dataview_edititem_method",
                    "dataview/api/dataview_enableselection_method",
                    "dataview/api/dataview_getfocus_method",
                    "dataview/api/dataview_getfocusindex_method",
                    "dataview/api/dataview_getfocusitem_method",
                    "dataview/api/dataview_paint_method",
                    "dataview/api/dataview_setfocus_method",
                    "dataview/api/dataview_setfocusindex_method",
                  ],
                },
                {
                  type: "category",
                  label: "Events",
                  items: [
                    "dataview/api/dataview_afterdrop_event",
                    "dataview/api/dataview_aftereditend_event",
                    "dataview/api/dataview_aftereditstart_event",
                    "dataview/api/dataview_beforedrag_event",
                    "dataview/api/dataview_beforedrop_event",
                    "dataview/api/dataview_beforeeditend_event",
                    "dataview/api/dataview_beforeeditstart_event",
                    "dataview/api/dataview_canceldrop_event",
                    "dataview/api/dataview_candrop_event",
                    "dataview/api/dataview_click_event",
                    "dataview/api/dataview_contextmenu_event",
                    "dataview/api/dataview_data_object", //todo
                    "dataview/api/dataview_doubleclick_event",
                    "dataview/api/dataview_dragin_event",
                    "dataview/api/dataview_dragout_event",
                    "dataview/api/dataview_dragstart_event",
                    "dataview/api/dataview_focuschange_event",
                    "dataview/api/dataview_itemmouseover_event",
                    "dataview/api/dataview_itemrightclick_event",
                    "dataview/api/dataview_selection_object", //todo
                  ],
                },
                {
                  type: "category",
                  label: "Properties",
                  items: [
                    "dataview/api/dataview_afterdrag_event",
                    "dataview/api/dataview_css_config",
                    "dataview/api/dataview_data_config",
                    "dataview/api/dataview_dragcopy_config",
                    "dataview/api/dataview_dragmode_config",
                    "dataview/api/dataview_editable_config",
                    "dataview/api/dataview_editing_config",
                    "dataview/api/dataview_eventhandlers_config",
                    "dataview/api/dataview_gap_config",
                    "dataview/api/dataview_height_config",
                    "dataview/api/dataview_itemheight_config",
                    "dataview/api/dataview_itemsinrow_config",
                    "dataview/api/dataview_keynavigation_config",
                    "dataview/api/dataview_multiselection_config",
                    "dataview/api/dataview_multiselectionmode_config",
                    "dataview/api/dataview_selection_config",
                    "dataview/api/dataview_template_config",
                  ],
                },
                {
                  type: "category",
                  label: "Selection API",
                  items: [
                    {
                      type: "category",
                      label: "Selection Methods",
                      items: [
                        "dataview/api/selection/selection_disable_method",
                        "dataview/api/selection/selection_enable_method",
                      ],
                    },
                    {
                      type: "category",
                      label: "Selection Events",
                      items: [
                        "dataview/api/selection/selection_afterselect_event",
                        "dataview/api/selection/selection_afterunselect_event",
                        "dataview/api/selection/selection_beforeselect_event",
                        "dataview/api/selection/selection_beforeunselect_event",
                      ],
                    },
                  ],
                },
              ],
            },
            "dataview/initialization",
            "dataview/configuration",
            "dataview/data_loading",
            "dataview/manipulating_data",
            "dataview/usage_selection",
            "dataview/customization",
            "dataview/events",
            "dataview/migration",
          ],
        },
        // end Dataview

        // // !!!! todo аццки большое количество файлов в форме

        // //Form
        {
          type: "category",
          label: "Form",
          collapsed: true,
          items: [
            "form/index",
            {
              type: "category",
              label: "API",
              collapsed: true,
              items: [
                // "calendar/api/api_overview", //todo
                {
                  type: "category",
                  label: "Methods",
                  collapsed: true,
                  items: [
                    "calendar/api/calendar_link_method",
                    "calendar/api/calendar_clear_method",
                    "calendar/api/calendar_paint_method",
                    "calendar/api/calendar_getcurrentmode_method",
                    "calendar/api/calendar_getvalue_method",
                    "calendar/api/calendar_setvalue_method",
                    "calendar/api/calendar_showdate_method",
                    "calendar/api/calendar_destructor_method",
                  ],
                },
                {
                  type: "category",
                  label: "Events",
                  collapsed: true,
                  items: [
                    "calendar/api/calendar_change_event",
                    "calendar/api/calendar_datehover_event",
                    "calendar/api/calendar_cancelclick_event",
                    "calendar/api/calendar_modechange_event",
                    "calendar/api/calendar_yearselected_event",
                    "calendar/api/calendar_monthselected_event",
                    "calendar/api/calendar_datemouseover_event",
                    "calendar/api/calendar_beforechange_event",
                  ],
                },
                {
                  type: "category",
                  label: "Properties",
                  collapsed: true,
                  items: [
                    "calendar/api/calendar_date_config",
                    "calendar/api/calendar_thismonthonly_config",
                    "calendar/api/calendar_disableddates_config",
                    "calendar/api/calendar_weeknumbers_config",
                    "calendar/api/calendar_dateformat_config",
                    "calendar/api/calendar_timepicker_config",
                    "calendar/api/calendar_timeformat_config",
                    "calendar/api/calendar_block_config",
                    "calendar/api/calendar_value_config",
                    "calendar/api/calendar_view_config",
                    "calendar/api/calendar_weekstart_config",
                    "calendar/api/calendar_css_config",
                    "calendar/api/calendar_mode_config",
                    "calendar/api/calendar_mark_config",
                    "calendar/api/calendar_range_config",
                    "calendar/api/calendar_width_config",
                  ],
                },
              ],
            },
            "form/how_to_start",
            "form/text",
            "form/input",
            "form/simplevault",
            "form/slider",
            "form/calendar",
            "form/timepicker",
            "form/api",
            "form/localization",
            "form/button",
            "form/handling_events",
            "form/radiogroup",
            "form/customization",
            "form/checkbox",
            "form/work_with_form",
            "form/block",
            "form/combo",
            "form/select",
            "form/migration",
            "form/colorpicker",
            "form/index",
            "form/configuration",
            "form/textarea",
          ],
        },
        // // end Form

        //Grid
        {
          type: "category",
          label: "Grid",
          items: [
            "grid/index",
            {
              type: "category",
              label: "API",
              items: [
                // "calendar/api/api_overview", //todo
                {
                  type: "category",
                  label: "Methods",
                  items: [
                    "grid/api/grid_addcellcss_method",
                    "grid/api/grid_addrowcss_method",
                    "grid/api/grid_addspan_method",
                    "grid/api/grid_adjustcolumnwidth_method",
                    "grid/api/grid_cellmousedown_event",
                    "grid/api/grid_destructor_method",
                    "grid/api/grid_edit_method",
                    "grid/api/grid_editcell_method",
                    "grid/api/grid_editend_method",
                    "grid/api/grid_getcellrect_method",
                    "grid/api/grid_getcolumn_method",
                    "grid/api/grid_getheaderfilter_method",
                    "grid/api/grid_getscrollstate_method",
                    "grid/api/grid_getsortingstate_method",
                    "grid/api/grid_getspan_method",
                    "grid/api/grid_hidecolumn_method",
                    "grid/api/grid_hiderow_method",
                    "grid/api/grid_iscolumnhidden_method",
                    "grid/api/grid_isrowhidden_method",
                    "grid/api/grid_paint_method",
                    "grid/api/grid_removecellcss_method",
                    "grid/api/grid_removerowcss_method",
                    "grid/api/grid_removespan_method",
                    "grid/api/grid_scroll_method",
                    "grid/api/grid_scrollto_method",
                    "grid/api/grid_setcolumns_method",
                    "grid/api/grid_showcolumn_method",
                    "grid/api/grid_showrow_method",
                  ],
                },
                {
                  type: "category",
                  label: "Events",
                  items: [
                    "grid/api/grid_aftercolumndrag_event",
                    "grid/api/grid_aftercolumndrop_event",
                    "grid/api/grid_aftercolumnhide_event",
                    "grid/api/grid_aftercolumnshow_event",
                    "grid/api/grid_aftereditend_event",
                    "grid/api/grid_aftereditstart_event",
                    "grid/api/grid_afterkeydown_event",
                    "grid/api/grid_afterresizeend_event",
                    "grid/api/grid_afterrowdrag_event",
                    "grid/api/grid_afterrowdrop_event",
                    "grid/api/grid_afterrowhide_event",
                    "grid/api/grid_afterrowshow_event",
                    "grid/api/grid_beforecolumndrag_event",
                    "grid/api/grid_beforecolumndrop_event",
                    "grid/api/grid_beforecolumnhide_event",
                    "grid/api/grid_beforecolumnshow_event",
                    "grid/api/grid_beforeeditend_event",
                    "grid/api/grid_beforeeditstart_event",
                    "grid/api/grid_beforekeydown_event",
                    "grid/api/grid_beforeresizestart_event",
                    "grid/api/grid_beforerowdrag_event",
                    "grid/api/grid_beforerowdrop_event",
                    "grid/api/grid_beforerowhide_event",
                    "grid/api/grid_beforerowshow_event",
                    "grid/api/grid_cancelcolumndrop_event",
                    "grid/api/grid_cancelrowdrop_event",
                    "grid/api/grid_cancolumndrop_event",
                    "grid/api/grid_canrowdrop_event",
                    "grid/api/grid_cellclick_event",
                    "grid/api/grid_celldblclick_event",
                    "grid/api/grid_cellmouseover_event",
                    "grid/api/grid_cellrightclick_event",
                    "grid/api/grid_data_object", // todo
                    "grid/api/grid_dragcolumnin_event",
                    "grid/api/grid_dragcolumnout_event",
                    "grid/api/grid_dragcolumnstart_event",
                    "grid/api/grid_dragrowin_event",
                    "grid/api/grid_dragrowout_event",
                    "grid/api/grid_dragrowstart_event",
                    "grid/api/grid_expand_event",
                    "grid/api/grid_export_object", //todo
                    "grid/api/grid_filterchange_event",
                    "grid/api/grid_footercellclick_event",
                    "grid/api/grid_footercelldblclick_event",
                    "grid/api/grid_footercellmousedown_event",
                    "grid/api/grid_footercellmouseover_event",
                    "grid/api/grid_footercellrightclick_event",
                    "grid/api/grid_headercellclick_event",
                    "grid/api/grid_headercelldblclick_event",
                    "grid/api/grid_headercellmousedown_event",
                    "grid/api/grid_headercellmouseover_event",
                    "grid/api/grid_headercellrightclick_event",
                    "grid/api/grid_headerinput_event",
                    "grid/api/grid_resize_event",
                    "grid/api/grid_scroll_event",
                    "grid/api/grid_sort_event",
                  ],
                },
                {
                  type: "category",
                  label: "Properties",
                  items: [
                    "grid/api/grid_adjust_config",
                    "grid/api/grid_autoemptyrow_config",
                    "grid/api/grid_autowidth_config",
                    "grid/api/grid_columns_config",
                    "grid/api/grid_columnsautowidth_config",
                    "grid/api/grid_css_config",
                    "grid/api/grid_data_config",
                    "grid/api/grid_dragcopy_config",
                    "grid/api/grid_dragitem_config",
                    "grid/api/grid_dragmode_config",
                    "grid/api/grid_editable_config",
                    "grid/api/grid_editing_config",
                    "grid/api/grid_eventhandlers_config",
                    "grid/api/grid_fittocontainer_config",
                    "grid/api/grid_footerrowheight_config",
                    "grid/api/grid_headerrowheight_config",
                    "grid/api/grid_headersort_config",
                    "grid/api/grid_height_config",
                    "grid/api/grid_htmlenable_config",
                    "grid/api/grid_keynavigation_config",
                    "grid/api/grid_leftsplit_config",
                    "grid/api/grid_multiselection_config",
                    "grid/api/grid_resizable_config",
                    "grid/api/grid_rowcss_config",
                    "grid/api/grid_rowheight_config",
                    "grid/api/grid_selection_config",
                    "grid/api/grid_sortable_config",
                    "grid/api/grid_spans_config",
                    "grid/api/grid_splitat_config",
                    "grid/api/grid_tooltip_config",
                    "grid/api/grid_width_config",
                  ],
                },
              ],
            },
            "grid/initialization",
            "grid/configuration",
            "grid/data_loading",
            "grid/usage",
            "grid/usage_selection",
            "grid/customization",
            "grid/events",
            "grid/migration",
          ],
        },
        // end Grid

        //Layout
        {
          type: "category",
          label: "Layout",
          items: [
            "layout/index",
            {
              type: "category",
              label: "API",
              items: [
                // "calendar/api/api_overview", //todo
                {
                  type: "category",
                  label: "Methods",
                  items: [
                    "layout/api/layout_addcell_method",
                    "layout/api/layout_attach_method",
                    "layout/api/layout_attachhtml_method",
                    "layout/api/layout_cell_method",
                    "layout/api/layout_collapse_method",
                    "layout/api/layout_destructor_method",
                    "layout/api/layout_expand_method",
                    "layout/api/layout_foreach_method",
                    "layout/api/layout_getcell_method",
                    "layout/api/layout_getparent_method",
                    "layout/api/layout_getwidget_method",
                    "layout/api/layout_hide_method",
                    "layout/api/layout_isvisible_method",
                    "layout/api/layout_paint_method",
                    "layout/api/layout_removecell_method",
                    "layout/api/layout_show_method",
                    "layout/api/layout_toggle_method",
                  ],
                },
                {
                  type: "category",
                  label: "Events",
                  items: [
                    "layout/api/layout_afteradd_event",
                    "layout/api/layout_aftercollapse_event",
                    "layout/api/layout_afterexpand_event",
                    "layout/api/layout_afterhide_event",
                    "layout/api/layout_afterremove_event",
                    "layout/api/layout_afterresizeend_event",
                    "layout/api/layout_aftershow_event",
                    "layout/api/layout_beforeadd_event",
                    "layout/api/layout_beforecollapse_event",
                    "layout/api/layout_beforeexpand_event",
                    "layout/api/layout_beforehide_event",
                    "layout/api/layout_beforeremove_event",
                    "layout/api/layout_beforeresizestart_event",
                    "layout/api/layout_beforeshow_event",
                    "layout/api/layout_resize_event",
                  ],
                },
                {
                  type: "category",
                  label: "Properties",
                  items: [
                    "layout/api/layout_activeview_config",
                    "layout/api/layout_align_config",
                    "layout/api/layout_collapsable_config",
                    "layout/api/layout_collapsed_config",
                    "layout/api/layout_cols_config",
                    "layout/api/layout_css_config",
                    "layout/api/layout_gravity_config",
                    "layout/api/layout_header_config",
                    "layout/api/layout_headerheight_config",
                    "layout/api/layout_headericon_config",
                    "layout/api/layout_headerimage_config",
                    "layout/api/layout_height_config",
                    "layout/api/layout_hidden_config",
                    "layout/api/layout_html_config",
                    "layout/api/layout_id_config",
                    "layout/api/layout_maxheight_config",
                    "layout/api/layout_maxwidth_config",
                    "layout/api/layout_minheight_config",
                    "layout/api/layout_minwidth_config",
                    "layout/api/layout_on_config",
                    "layout/api/layout_padding_config",
                    "layout/api/layout_resizable_config",
                    "layout/api/layout_rows_config",
                    "layout/api/layout_type_config",
                    "layout/api/layout_views_config",
                    "layout/api/layout_width_config",
                  ],
                },
              ],
            },
            "layout/init",

            "layout/configuration",
            "layout/layout_structure",
            "layout/layout_patterns",
            "layout/cell_configuration",

            "layout/work_with_layout",
            "layout/customization",
            "layout/events",
            "layout/migration",
          ],
        },
        // end Layout

        //List
        {
          type: "category",
          label: "List",
          items: [
            "list/index",
            {
              type: "category",
              label: "API",
              items: [
                // "calendar/api/api_overview", //todo
                {
                  type: "category",
                  label: "Methods",
                  items: [
                    "list/api/list_destructor_method",
                    "list/api/list_disableselection_method",
                    "list/api/list_edit_method",
                    "list/api/list_edititem_method",
                    "list/api/list_enableselection_method",
                    "list/api/list_getfocus_method",
                    "list/api/list_getfocusindex_method",
                    "list/api/list_getfocusitem_method",
                    "list/api/list_paint_method",
                    "list/api/list_setfocus_method",
                    "list/api/list_setfocusindex_method",
                  ],
                },
                {
                  type: "category",
                  label: "Events",
                  items: [
                    "list/api/list_afterdrag_event",
                    "list/api/list_afterdrop_event",
                    "list/api/list_aftereditend_event",
                    "list/api/list_aftereditstart_event",
                    "list/api/list_beforedrag_event",
                    "list/api/list_beforedrop_event",
                    "list/api/list_beforeeditend_event",
                    "list/api/list_beforeeditstart_event",
                    "list/api/list_canceldrop_event",
                    "list/api/list_candrop_event",
                    "list/api/list_click_event",
                    "list/api/list_contextmenu_event",
                    "list/api/list_data_object", //todo
                    "list/api/list_doubleclick_event",
                    "list/api/list_dragin_event",
                    "list/api/list_dragout_event",
                    "list/api/list_dragstart_event",
                    "list/api/list_focuschange_event",
                    "list/api/list_itemmouseover_event",
                    "list/api/list_itemrightclick_event",
                    "list/api/list_selection_object",
                  ],
                },
                {
                  type: "category",
                  label: "Properties",
                  items: [
                    "list/api/list_css_config",
                    "list/api/list_data_config",
                    "list/api/list_dragcopy_config",
                    "list/api/list_dragmode_config",
                    "list/api/list_dropbehaviour_config",
                    "list/api/list_editable_config",
                    "list/api/list_editing_config",
                    "list/api/list_eventhandlers_config",
                    "list/api/list_height_config",
                    "list/api/list_itemheight_config",
                    "list/api/list_keynavigation_config",
                    "list/api/list_multiselection_config",
                    "list/api/list_multiselectionmode_config",
                    "list/api/list_selection_config",
                    "list/api/list_template_config",
                    "list/api/list_virtual_config",
                  ],
                },

                {
                  type: "category",
                  label: "Selection API",
                  items: [
                    {
                      type: "category",
                      label: "Methods",
                      items: [
                        "list/api/selection/selection_disable_method",
                        "list/api/selection/selection_enable_method",
                      ],
                    },

                    {
                      type: "category",
                      label: "Events",
                      items: [
                        "list/api/selection/selection_afterselect_event",
                        "list/api/selection/selection_afterunselect_event",
                        "list/api/selection/selection_beforeselect_event",
                        "list/api/selection/selection_beforeunselect_event",
                      ],
                    },
                  ],
                },
              ],
            },
            "list/initialization",
            "list/configuration",
            "list/load_data",
            "list/work_with_list",
            "list/usage_selection",
            "list/customization",
            "list/events",
            "list/migration",
          ],
        },
        // end List

        // "menu/api/selection_afterunselect_event",
        // "menu/api/selection_beforeselect_event",
        // "menu/api/selection_beforeunselect_event",
        // "menu/api/selection_afterselect_event",

        // "menu/api/selection_getcell_method",
        // "menu/api/selection_getcells_method",
        // "menu/api/selection_removecell_method",
        // "menu/api/selection_enable_method",
        // "menu/api/selection_disable_method",
        // "menu/api/selection_setcell_method",

        //Menu
        {
          type: "category",
          label: "Menu",
          items: [
            "menu/index",
            {
              type: "category",
              label: "API",
              items: [
                // "calendar/api/api_overview", //todo //todo
                {
                  type: "category",
                  label: "Methods",
                  items: [
                    "menu/api/menu_destructor_method",
                    "menu/api/menu_disable_method",
                    "menu/api/menu_enable_method",
                    "menu/api/menu_getselected_method",
                    "menu/api/menu_hide_method",
                    "menu/api/menu_isdisabled_method",
                    "menu/api/menu_isselected_method",
                    "menu/api/menu_paint_method",
                    "menu/api/menu_select_method",
                    "menu/api/menu_show_method",
                    "menu/api/menu_showat_method",
                    "menu/api/menu_unselect_method",
                  ],
                },
                {
                  type: "category",
                  label: "Events",
                  items: [
                    "menu/api/menu_afterhide_event",
                    "menu/api/menu_beforehide_event",
                    "menu/api/menu_click_event",
                    "menu/api/menu_inputblur_event",
                    "menu/api/menu_inputcreated_event",
                    "menu/api/menu_inputfocus_event",
                    "menu/api/menu_openmenu_event",
                  ],
                },
                {
                  type: "category",
                  label: "Properties",
                  items: [
                    "menu/api/menu_css_config",
                    "menu/api/menu_data_config",
                    "menu/api/menu_menucss_config",
                    "menu/api/menu_navigationtype_config",
                  ],
                },
                {
                  type: "category",
                  label: "Selection API",
                  items: [
                    {
                      type: "category",
                      label: "Methods",
                      items: [],
                    },

                    {
                      type: "category",
                      label: "Events",
                      items: [],
                    },
                  ],
                },
              ],
            },
            "menu/how_to_start",
            "menu/configuring_menu_items",
            "menu/from_script",
            "menu/work_with_menu",
            "menu/creating_context_menu",
            "menu/fa_icons",
            "menu/handling_events",
            // "menu/migration",
          ],
        },
        // end Menu

        //Message //???? todo где API????
        {
          type: "category",
          label: "Message",
          items: [
            "message/index",
            {
              type: "category",
              label: "API",
              items: [
                // "calendar/api/api_overview", //todo //todo
                {
                  type: "category",
                  label: "Methods",
                  items: [
                    "calendar/api/calendar_clear_method",
                    "calendar/api/calendar_destructor_method",
                    "calendar/api/calendar_getcurrentmode_method",
                    "calendar/api/calendar_getvalue_method",
                    "calendar/api/calendar_link_method",
                    "calendar/api/calendar_paint_method",
                    "calendar/api/calendar_setvalue_method",
                    "calendar/api/calendar_showdate_method",
                  ],
                },
                {
                  type: "category",
                  label: "Events",
                  items: [
                    "calendar/api/calendar_beforechange_event",
                    "calendar/api/calendar_cancelclick_event",
                    "calendar/api/calendar_change_event",
                    "calendar/api/calendar_datehover_event",
                    "calendar/api/calendar_datemouseover_event",
                    "calendar/api/calendar_modechange_event",
                    "calendar/api/calendar_monthselected_event",
                    "calendar/api/calendar_yearselected_event",
                  ],
                },
                {
                  type: "category",
                  label: "Properties",
                  items: [
                    "calendar/api/calendar_block_config",
                    "calendar/api/calendar_css_config",
                    "calendar/api/calendar_date_config",
                    "calendar/api/calendar_dateformat_config",
                    "calendar/api/calendar_disableddates_config",
                    "calendar/api/calendar_mark_config",
                    "calendar/api/calendar_mode_config",
                    "calendar/api/calendar_range_config",
                    "calendar/api/calendar_thismonthonly_config",
                    "calendar/api/calendar_timeformat_config",
                    "calendar/api/calendar_timepicker_config",
                    "calendar/api/calendar_value_config",
                    "calendar/api/calendar_view_config",
                    "calendar/api/calendar_weeknumbers_config",
                    "calendar/api/calendar_weekstart_config",
                    "calendar/api/calendar_width_config",
                  ],
                },
              ],
            },
            "message/overview",
            "message/creating_message",
            "message/configuration",
            "message/customization",
            "message/migration",
          ],
        },
        // end Message

        //Pagination
        {
          type: "category",
          label: "Pagination",
          items: [
            "pagination/index",
            {
              type: "category",
              label: "API",
              items: [
                "pagination/api/api_overview",
                {
                  type: "category",
                  label: "Methods",
                  items: [
                    "pagination/api/pagination_destructor_method",
                    "pagination/api/pagination_getpage_method",
                    "pagination/api/pagination_getpagescount_method",
                    "pagination/api/pagination_getpagesize_method",
                    "pagination/api/pagination_setpage_method",
                    "pagination/api/pagination_setpagesize_method",
                  ],
                },
                {
                  type: "category",
                  label: "Events",
                  items: ["pagination/api/pagination_change_event"],
                },
                {
                  type: "category",
                  label: "Properties",
                  items: [
                    "pagination/api/pagination_css_config",
                    "pagination/api/pagination_data_config",
                    "pagination/api/pagination_inputwidth_config",
                    "pagination/api/pagination_page_config",
                    "pagination/api/pagination_pagesize_config",
                  ],
                },
              ],
            },
            "pagination/init",
            "pagination/configuration",
            "pagination/usage",
            "pagination/customization",
            "pagination/handling_events",
          ],
        },
        // end Pagination

        //Popup
        {
          type: "category",
          label: "Popup",
          items: [
            "popup/index",
            {
              type: "category",
              label: "API",
              items: [
                // "calendar/api/api_overview", //todo //todo

                {
                  type: "category",
                  label: "Methods",
                  items: [
                    "popup/api/popup_attach_method",
                    "popup/api/popup_attachhtml_method",
                    "popup/api/popup_destructor_method",
                    "popup/api/popup_getcontainer_method",
                    "popup/api/popup_getwidget_method",
                    "popup/api/popup_hide_method",
                    "popup/api/popup_isvisible_method",
                    "popup/api/popup_paint_method",
                    "popup/api/popup_show_method",
                  ],
                },
                {
                  type: "category",
                  label: "Events",
                  items: [
                    "popup/api/popup_afterhide_event",
                    "popup/api/popup_aftershow_event",
                    "popup/api/popup_beforehide_event",
                    "popup/api/popup_beforeshow_event",
                    "popup/api/popup_click_event",
                  ],
                },
                {
                  type: "category",
                  label: "Properties",
                  items: ["popup/api/popup_css_config"],
                },
              ],
            },
            "popup/initialization",
            "popup/work_with_popup",
            "popup/customization",
            "popup/event_handling",
          ],
        },
        // end Popup

        //Ribbon
        {
          type: "category",
          label: "Ribbon",
          items: [
            "ribbon/index",
            {
              type: "category",
              label: "API",
              items: [
                // "calendar/api/api_overview", //todo

                {
                  type: "category",
                  label: "Methods",
                  items: [
                    "ribbon/api/ribbon_destructor_method",
                    "ribbon/api/ribbon_disable_method",
                    "ribbon/api/ribbon_enable_method",
                    "ribbon/api/ribbon_getselected_method",
                    "ribbon/api/ribbon_getstate_method",
                    "ribbon/api/ribbon_hide_method",
                    "ribbon/api/ribbon_isdisabled_method",
                    "ribbon/api/ribbon_isselected_method",
                    "ribbon/api/ribbon_paint_method",
                    "ribbon/api/ribbon_select_method",
                    "ribbon/api/ribbon_setstate_method",
                    "ribbon/api/ribbon_show_method",
                    "ribbon/api/ribbon_unselect_method",
                  ],
                },
                {
                  type: "category",
                  label: "Events",
                  items: [
                    "ribbon/api/ribbon_click_event",
                    "ribbon/api/ribbon_inputblur_event",
                    "ribbon/api/ribbon_inputcreated_event",
                    "ribbon/api/ribbon_inputfocus_event",
                    "ribbon/api/ribbon_openmenu_event",
                  ],
                },
                {
                  type: "category",
                  label: "Properties",
                  items: [
                    "ribbon/api/ribbon_css_config",
                    "ribbon/api/ribbon_data_config",
                    "ribbon/api/ribbon_menucss_config",
                  ],
                },
              ],
            },
            "ribbon/how_to_start",

            {
              type: "category",
              label: "List of Ribbon controls",
              items: [
                "ribbon/controls",
                "ribbon/block",
                "ribbon/button",
                "ribbon/customhtmlbutton",
                "ribbon/image_button",
                "ribbon/input",
                "ribbon/navitem",
                "ribbon/selectbutton",
                "ribbon/separator",
                "ribbon/spacer",
                "ribbon/title",
              ]
            },
            "ribbon/loading_json",
            "ribbon/operating_ribbon",
            "ribbon/fa_icons",
            "ribbon/handling_events",
            // "ribbon/migration",
          ],
        },
        // end Ribbon

        //Sidebar
        {
          type: "category",
          label: "Sidebar",
          items: [
            "sidebar/index",
            {
              type: "category",
              label: "API",
              items: [
                // "calendar/api/api_overview", //todo //todo
                {
                  type: "category",
                  label: "Methods",
                  items: [
                    "sidebar/api/sidebar_collapse_method",
                    "sidebar/api/sidebar_destructor_method",
                    "sidebar/api/sidebar_disable_method",
                    "sidebar/api/sidebar_enable_method",
                    "sidebar/api/sidebar_expand_method",
                    "sidebar/api/sidebar_getselected_method",
                    "sidebar/api/sidebar_hide_method",
                    "sidebar/api/sidebar_iscollapsed_method",
                    "sidebar/api/sidebar_isdisabled_method",
                    "sidebar/api/sidebar_isselected_method",
                    "sidebar/api/sidebar_paint_method",
                    "sidebar/api/sidebar_select_method",
                    "sidebar/api/sidebar_show_method",
                    "sidebar/api/sidebar_toggle_method",
                    "sidebar/api/sidebar_unselect_method",
                  ],
                },
                {
                  type: "category",
                  label: "Events",
                  items: [
                    "sidebar/api/sidebar_aftercollapse_event",
                    "sidebar/api/sidebar_afterexpand_event",
                    "sidebar/api/sidebar_afterhide_event",
                    "sidebar/api/sidebar_beforecollapse_event",
                    "sidebar/api/sidebar_beforeexpand_event",
                    "sidebar/api/sidebar_beforehide_event",
                    "sidebar/api/sidebar_click_event",
                    "sidebar/api/sidebar_data_object", //todo что это?
                    "sidebar/api/sidebar_inputblur_event",
                    "sidebar/api/sidebar_inputcreated_event",
                    "sidebar/api/sidebar_inputfocus_event",
                    "sidebar/api/sidebar_openmenu_event",
                    "sidebar/api/sidebar_toggle_event",
                  ],
                },
                {
                  type: "category",
                  label: "Properties",
                  items: [
                    "sidebar/api/sidebar_collapsed_config",
                    "sidebar/api/sidebar_css_config",
                    "sidebar/api/sidebar_data_config",
                    "sidebar/api/sidebar_menucss_config",
                    "sidebar/api/sidebar_minwidth_config",
                    "sidebar/api/sidebar_width_config",
                  ],
                },
              ],
            },
            "sidebar/init",
            {
              type: "category",
              label: "List of Sidebar сontrols",
              items: [
                "sidebar/customhtmlbutton",
                "sidebar/menuitem",
                "sidebar/navitem",
                "sidebar/separator",
                "sidebar/spacer",
                "sidebar/title",
              ],
            },
            "sidebar/data_loading",
            "sidebar/sidebar_config",
            "sidebar/work_with_sidebar",
            "sidebar/customization",
            "sidebar/events",
            "sidebar/migration",
          ],
        },
        // end Sidebar

        //Slider
        {
          type: "category",
          label: "Slider",
          items: [
            "slider/index",
            {
              type: "category",
              label: "API",
              items: [
                // "calendar/api/api_overview", //todo //todo

                {
                  type: "category",
                  label: "Methods",
                  items: [
                    "slider/api/slider_destructor_method",
                    "slider/api/slider_disable_method",
                    "slider/api/slider_enable_method",
                    "slider/api/slider_getvalue_method",
                    "slider/api/slider_isdisabled_method",
                    "slider/api/slider_paint_method",
                    "slider/api/slider_setvalue_method",
                  ],
                },
                {
                  type: "category",
                  label: "Events",
                  items: [
                    "slider/api/slider_change_event",
                    "slider/api/slider_mousedown_event",
                    "slider/api/slider_mouseup_event",
                  ],
                },
                {
                  type: "category",
                  label: "Properties",
                  items: [
                    "slider/api/slider_css_config",
                    "slider/api/slider_help_config",
                    "slider/api/slider_helpmessage_config",
                    "slider/api/slider_hiddenlabel_config",
                    "slider/api/slider_inverse_config",
                    "slider/api/slider_label_config",
                    "slider/api/slider_labelinline_config",
                    "slider/api/slider_labelposition_config",
                    "slider/api/slider_labelwidth_config",
                    "slider/api/slider_majortick_config",
                    "slider/api/slider_max_config",
                    "slider/api/slider_min_config",
                    "slider/api/slider_mode_config",
                    "slider/api/slider_range_config",
                    "slider/api/slider_step_config",
                    "slider/api/slider_thumblabel_config",
                    "slider/api/slider_tick_config",
                    "slider/api/slider_ticktemplate_config",
                    "slider/api/slider_tooltip_config",
                    "slider/api/slider_value_config",
                  ],
                },
              ],
            },
            "slider/initializing_slider",
            "slider/configuring_slider",
            "slider/range_slider",
            "slider/usage",
            "slider/customization",
            "slider/handling_events",
            "slider/migration",
          ],
        },
        // end Slider

        //Tabbar
        {
          type: "category",
          label: "Tabbar",
          items: [
            "tabbar/index",
            {
              type: "category",
              label: "API",
              items: [
                // "calendar/api/api_overview", //todo
                {
                  type: "category",
                  label: "Methods",
                  items: [
                    "tabbar/api/tabbar_activetab_config",
                    "tabbar/api/tabbar_addcell_method",
                    "tabbar/api/tabbar_addtab_method",
                    "tabbar/api/tabbar_destructor_method",
                    "tabbar/api/tabbar_disabletab_method",
                    "tabbar/api/tabbar_enabletab_method",
                    "tabbar/api/tabbar_getactive_method",
                    "tabbar/api/tabbar_getcell_method",
                    "tabbar/api/tabbar_getid_method",
                    "tabbar/api/tabbar_getwidget_method",
                    "tabbar/api/tabbar_isdisabled_method",
                    "tabbar/api/tabbar_nocontent_config",
                    "tabbar/api/tabbar_padding_config",
                    "tabbar/api/tabbar_paint_method",
                    "tabbar/api/tabbar_removecell_method",
                    "tabbar/api/tabbar_removetab_method",
                    "tabbar/api/tabbar_setactive_method",
                  ],
                },
                {
                  type: "category",
                  label: "Events",
                  items: [
                    "tabbar/api/tabbar_afterclose_event",
                    "tabbar/api/tabbar_beforeclose_event",
                    "tabbar/api/tabbar_change_event",
                    "tabbar/api/tabbar_close_event",
                  ],
                },
                {
                  type: "category",
                  label: "Properties",
                  items: [
                    "tabbar/api/tabbar_activeview_config",
                    "tabbar/api/tabbar_closable_config",
                    "tabbar/api/tabbar_closebuttons_config",
                    "tabbar/api/tabbar_css_config",
                    "tabbar/api/tabbar_disabled_config",
                    "tabbar/api/tabbar_html_config",
                    "tabbar/api/tabbar_id_config",
                    "tabbar/api/tabbar_mode_config",
                    "tabbar/api/tabbar_tabalign_config",
                    "tabbar/api/tabbar_tabautoheight_config",
                    "tabbar/api/tabbar_tabautowidth_config",
                    "tabbar/api/tabbar_tabheight_config",
                    "tabbar/api/tabbar_tabwidth_config",
                    "tabbar/api/tabbar_views_config",
                  ],
                },
              ],
            },
            "tabbar/init",
            "tabbar/configuring_tabbar",
            "tabbar/work_with_tabbar",
            "tabbar/customization",
            "tabbar/events",
            "tabbar/migration",
          ],
        },
        // end Tabbar

        //Timepicker
        {
          type: "category",
          label: "Timepicker",
          collapsed: false,
          items: [
            "timepicker/index",
            {
              type: "category",
              label: "API",
              items: [
                // "calendar/api/api_overview", //todo
                {
                  type: "category",
                  label: "Methods",
                  items: [
                    "timepicker/api/timepicker_clear_method",
                    "timepicker/api/timepicker_destructor_method",
                    "timepicker/api/timepicker_getvalue_method",
                    "timepicker/api/timepicker_paint_method",
                    "timepicker/api/timepicker_setvalue_method",
                  ],
                },
                {
                  type: "category",
                  label: "Events",
                  items: [
                    "timepicker/api/timepicker_afterapply_event",
                    "timepicker/api/timepicker_afterclose_event",
                    "timepicker/api/timepicker_apply_event",
                    "timepicker/api/timepicker_beforeapply_event",
                    "timepicker/api/timepicker_beforeclose_event",
                    "timepicker/api/timepicker_change_event",
                    "timepicker/api/timepicker_close_event",
                    "timepicker/api/timepicker_config_object", //todo
                    "timepicker/api/timepicker_events_object", //todo
                    "timepicker/api/timepicker_layout_object", //todo
                    "timepicker/api/timepicker_save_event",
                  ],
                },
                {
                  type: "category",
                  label: "Properties",
                  items: [
                    "timepicker/api/timepicker_actions_config",
                    "timepicker/api/timepicker_controls_config",
                    "timepicker/api/timepicker_css_config",
                    "timepicker/api/timepicker_timeformat_config",
                    "timepicker/api/timepicker_value_config",
                    "timepicker/api/timepicker_valueformat_config",
                  ],
                },
              ],
            },
            "timepicker/initialization",
            "timepicker/configuration",
            "timepicker/usage",
            "timepicker/customization",
            "timepicker/handling_events",
            "timepicker/migration",
          ],
        },
        // end Timepicker

        //Toolbar
        {
          type: "category",
          label: "Toolbar",
          items: [
            "toolbar/index",
            {
              type: "category",
              label: "API",
              items: [
                // "calendar/api/api_overview", //todo
                {
                  type: "category",
                  label: "Methods",
                  items: [
                    "toolbar/api/toolbar_destructor_method",
                    "toolbar/api/toolbar_disable_method",
                    "toolbar/api/toolbar_enable_method",
                    "toolbar/api/toolbar_getselected_method",
                    "toolbar/api/toolbar_getstate_method",
                    "toolbar/api/toolbar_hide_method",
                    "toolbar/api/toolbar_isdisabled_method",
                    "toolbar/api/toolbar_isselected_method",
                    "toolbar/api/toolbar_paint_method",
                    "toolbar/api/toolbar_select_method",
                    "toolbar/api/toolbar_setstate_method",
                    "toolbar/api/toolbar_show_method",
                    "toolbar/api/toolbar_unselect_method",
                  ],
                },
                {
                  type: "category",
                  label: "Events",
                  items: [
                    "toolbar/api/toolbar_afterhide_event",
                    "toolbar/api/toolbar_beforehide_event",
                    "toolbar/api/toolbar_click_event",
                    "toolbar/api/toolbar_data_object", //todo
                    "toolbar/api/toolbar_inputblur_event",
                    "toolbar/api/toolbar_inputcreated_event",
                    "toolbar/api/toolbar_inputfocus_event",
                    "toolbar/api/toolbar_openmenu_event",
                  ],
                },
                {
                  type: "category",
                  label: "Properties",
                  items: [
                    "toolbar/api/toolbar_css_config",
                    "toolbar/api/toolbar_data_config",
                    "toolbar/api/toolbar_menucss_config",
                  ],
                },
              ],
            },
            "toolbar/how_to_start",

            "toolbar/controls_list",
            "toolbar/button",
            "toolbar/customhtmlbutton",
            "toolbar/image_button",
            "toolbar/input",
            "toolbar/menuitem",
            "toolbar/navitem",
            "toolbar/selectbutton",
            "toolbar/separator",
            "toolbar/spacer",




            "toolbar/regular_button",
            "toolbar/icon_button",
            "toolbar/object_constructor",
            "toolbar/dhxbutton",
            "toolbar/common_methods",
            "toolbar/image_button_text",
            "toolbar/text",
            "toolbar/api",
            "toolbar/handling_events",
            "toolbar/customization",
            "toolbar/block",
            "toolbar/load_data",
            "toolbar/migration",
            "toolbar/index",
            "toolbar/menu_item",
          ],
        },
        // end Toolbar

        //Tree
        {
          type: "category",
          label: "Tree",
          items: [
            "tree/index",
            {
              type: "category",
              label: "API",
              items: [
                // "calendar/api/api_overview", //todo
                {
                  type: "category",
                  label: "Methods",
                  items: [
                    "tree/api/tree_checkitem_method",
                    "tree/api/tree_close_method",
                    "tree/api/tree_closeall_method",
                    "tree/api/tree_collapse_method",
                    "tree/api/tree_collapseall_method",
                    "tree/api/tree_destructor_method",
                    "tree/api/tree_edititem_method",
                    "tree/api/tree_expand_method",
                    "tree/api/tree_expandall_method",
                    "tree/api/tree_focusitem_method",
                    "tree/api/tree_getchecked_method",
                    "tree/api/tree_getstate_method",
                    "tree/api/tree_open_method",
                    "tree/api/tree_openall_method",
                    "tree/api/tree_paint_method",
                    "tree/api/tree_setstate_method",
                    "tree/api/tree_toggle_method",
                    "tree/api/tree_uncheckitem_method",
                    "tree/api/tree_uncheckitemnew_method",
                  ],
                },
                {
                  type: "category",
                  label: "Events",
                  items: [
                    "tree/api/tree_aftercollapse_event",
                    "tree/api/tree_afterdrag_event",
                    "tree/api/tree_afterdrop_event",
                    "tree/api/tree_aftereditend_event",
                    "tree/api/tree_aftereditstart_event",
                    "tree/api/tree_afterexpand_event",
                    "tree/api/tree_beforecollapse_event",
                    "tree/api/tree_beforedrag_event",
                    "tree/api/tree_beforedrop_event",
                    "tree/api/tree_beforeeditend_event",
                    "tree/api/tree_beforeeditstart_event",
                    "tree/api/tree_beforeexpand_event",
                    "tree/api/tree_canceldrop_event",
                    "tree/api/tree_candrop_event",
                    "tree/api/tree_data_object", //
                    "tree/api/tree_dragin_event",
                    "tree/api/tree_dragout_event",
                    "tree/api/tree_dragstart_event",
                    "tree/api/tree_focuschange_event",
                    "tree/api/tree_itemclick_event",
                    "tree/api/tree_itemcontextmenu_event",
                    "tree/api/tree_itemdblclick_event",
                    "tree/api/tree_itemrightclick_event",
                  ],
                },
                {
                  type: "category",
                  label: "Properties",
                  items: [
                    "tree/api/tree_autoload_config",
                    "tree/api/tree_checkbox_config",
                    "tree/api/tree_css_config",
                    "tree/api/tree_data_config",
                    "tree/api/tree_dragcopy_config",
                    "tree/api/tree_dragmode_config",
                    "tree/api/tree_dropbehaviour_config",
                    "tree/api/tree_editable_config",
                    "tree/api/tree_editing_config",
                    "tree/api/tree_icon_config",
                    "tree/api/tree_isfolder_config",
                    "tree/api/tree_keynavigation_config",
                    "tree/api/tree_rootid_config",
                    "tree/api/tree_selection_config",
                  ],
                },
                {
                  type: "category",
                  label: "Selection API",
                  items: [
                    {
                      type: "category",
                      label: "Methods",
                      items: [
                        "tree/api/selection/selection_disable_method",
                        "tree/api/selection/selection_enable_method",
                      ],
                    },

                    {
                      type: "category",
                      label: "Events",
                      items: [
                        "tree/api/selection/selection_afterselect_event",
                        "tree/api/selection/selection_afterunselect_event",
                        "tree/api/selection/selection_beforeselect_event",
                        "tree/api/selection/selection_beforeunselect_event",
                      ],
                    },
                  ],
                },
              ],
            },
            "tree/compatibility_with_other_dhtmlx_components",
            "tree/loading_data",
            "tree/serialization_caching_and_removing_tree",
            "tree/searching_and_sorting_in_tree",
            "tree/work_with_tree",
            "tree/navigation_and_selection_in_tree",
            "tree/increasing_tree_s_performance",
            "tree/api",
            "tree/syntax_templates",
            "tree/usage_selection",
            "tree/setting_tree_appearance",
            "tree/simultaneous_server_update",
            "tree/initialization_of_dhtmlxtree",
            "tree/events_handling",
            "tree/migration",
            "tree/checkboxes_manipulation",
            "tree/drag_and_drop_handling",
            "tree/nodes_manipulation",
            "tree/index",
            "tree/configuration",
            "tree/radio_buttons_manipulation",
          ],
        },
        // end Tree

        //TreeGrid
        {
          type: "category",
          label: "TreeGrid",
          items: [
            "treegrid/index",
            {
              type: "category",
              label: "API",
              items: [
                // "calendar/api/api_overview", //todo //todo
                {
                  type: "category",
                  label: "Methods",
                  items: [
                    "treegrid/api/treegrid_addcellcss_method",
                    "treegrid/api/treegrid_addrowcss_method",
                    "treegrid/api/treegrid_addspan_method",
                    "treegrid/api/treegrid_adjustcolumnwidth_method",
                    "treegrid/api/treegrid_collapse_method",
                    "treegrid/api/treegrid_collapseall_method",
                    "treegrid/api/treegrid_destructor_method",
                    "treegrid/api/treegrid_edit_method",
                    "treegrid/api/treegrid_editcell_method",
                    "treegrid/api/treegrid_editend_method",
                    "treegrid/api/treegrid_expand_method",
                    "treegrid/api/treegrid_expandall_method",
                    "treegrid/api/treegrid_getcellrect_method",
                    "treegrid/api/treegrid_getcolumn_method",
                    "treegrid/api/treegrid_getheaderfilter_method",
                    "treegrid/api/treegrid_getscrollstate_method",
                    "treegrid/api/treegrid_getsortingstate_method",
                    "treegrid/api/treegrid_getspan_method",
                    "treegrid/api/treegrid_groupby_method",
                    "treegrid/api/treegrid_hidecolumn_method",
                    "treegrid/api/treegrid_hiderow_method",
                    "treegrid/api/treegrid_iscolumnhidden_method",
                    "treegrid/api/treegrid_isrowhidden_method",
                    "treegrid/api/treegrid_paint_method",
                    "treegrid/api/treegrid_removecellcss_method",
                    "treegrid/api/treegrid_removerowcss_method",
                    "treegrid/api/treegrid_removespan_method",
                    "treegrid/api/treegrid_scroll_method",
                    "treegrid/api/treegrid_scrollto_method",
                    "treegrid/api/treegrid_setcolumns_method",
                    "treegrid/api/treegrid_showcolumn_method",
                    "treegrid/api/treegrid_showrow_method",
                    "treegrid/api/treegrid_ungroup_method",
                  ],
                },
                {
                  type: "category",
                  label: "Events",
                  items: [
                    "treegrid/api/treegrid_aftercollapse_event",
                    "treegrid/api/treegrid_aftercolumndrag_event",
                    "treegrid/api/treegrid_aftercolumndrop_event",
                    "treegrid/api/treegrid_aftercolumnhide_event",
                    "treegrid/api/treegrid_aftercolumnshow_event",
                    "treegrid/api/treegrid_aftereditend_event",
                    "treegrid/api/treegrid_aftereditstart_event",
                    "treegrid/api/treegrid_afterexpand_event",
                    "treegrid/api/treegrid_afterresizeend_event",
                    "treegrid/api/treegrid_afterrowdrag_event",
                    "treegrid/api/treegrid_afterrowdrop_event",
                    "treegrid/api/treegrid_afterrowhide_event",
                    "treegrid/api/treegrid_afterrowshow_event",
                    "treegrid/api/treegrid_beforecollapse_event",
                    "treegrid/api/treegrid_beforecolumndrag_event",
                    "treegrid/api/treegrid_beforecolumndrop_event",
                    "treegrid/api/treegrid_beforecolumnhide_event",
                    "treegrid/api/treegrid_beforecolumnshow_event",
                    "treegrid/api/treegrid_beforeeditend_event",
                    "treegrid/api/treegrid_beforeeditstart_event",
                    "treegrid/api/treegrid_beforeexpand_event",
                    "treegrid/api/treegrid_beforeresizestart_event",
                    "treegrid/api/treegrid_beforerowdrag_event",
                    "treegrid/api/treegrid_beforerowdrop_event",
                    "treegrid/api/treegrid_beforerowhide_event",
                    "treegrid/api/treegrid_beforerowshow_event",
                    "treegrid/api/treegrid_cancelcolumndrop_event",
                    "treegrid/api/treegrid_cancelrowdrop_event",
                    "treegrid/api/treegrid_cancolumndrop_event",
                    "treegrid/api/treegrid_canrowdrop_event",
                    "treegrid/api/treegrid_cellclick_event",
                    "treegrid/api/treegrid_celldblclick_event",
                    "treegrid/api/treegrid_cellmousedown_event",
                    "treegrid/api/treegrid_cellmouseover_event",
                    "treegrid/api/treegrid_cellrightclick_event",
                    "treegrid/api/treegrid_data_object", //todo
                    "treegrid/api/treegrid_dragcolumnin_event",
                    "treegrid/api/treegrid_dragcolumnout_event",
                    "treegrid/api/treegrid_dragcolumnstart_event",
                    "treegrid/api/treegrid_dragrowin_event",
                    "treegrid/api/treegrid_dragrowout_event",
                    "treegrid/api/treegrid_dragrowstart_event",
                    "treegrid/api/treegrid_expand_event",
                    "treegrid/api/treegrid_export_object", //todo
                    "treegrid/api/treegrid_filterchange_event",
                    "treegrid/api/treegrid_footercellclick_event",
                    "treegrid/api/treegrid_footercelldblclick_event",
                    "treegrid/api/treegrid_footercellmousedown_event",
                    "treegrid/api/treegrid_footercellmouseover_event",
                    "treegrid/api/treegrid_footercellrightclick_event",
                    "treegrid/api/treegrid_headercellclick_event",
                    "treegrid/api/treegrid_headercelldblclick_event",
                    "treegrid/api/treegrid_headercellmousedown_event",
                    "treegrid/api/treegrid_headercellmouseover_event",
                    "treegrid/api/treegrid_headercellrightclick_event",
                    "treegrid/api/treegrid_headerinput_event",
                    "treegrid/api/treegrid_resize_event",
                    "treegrid/api/treegrid_scroll_event",
                    "treegrid/api/treegrid_sort_event",
                  ],
                },
                {
                  type: "category",
                  label: "Properties",
                  items: [
                    "treegrid/api/treegrid_adjust_config",
                    "treegrid/api/treegrid_autoemptyrow_config",
                    "treegrid/api/treegrid_autowidth_config",
                    "treegrid/api/treegrid_columns_config",
                    "treegrid/api/treegrid_columnsautowidth_config",
                    "treegrid/api/treegrid_css_config",
                    "treegrid/api/treegrid_data_config",
                    "treegrid/api/treegrid_dragcopy_config",
                    "treegrid/api/treegrid_dragitem_config",
                    "treegrid/api/treegrid_dragmode_config",
                    "treegrid/api/treegrid_editable_config",
                    "treegrid/api/treegrid_editing_config",
                    "treegrid/api/treegrid_eventhandlers_config",
                    "treegrid/api/treegrid_fittocontainer_config",
                    "treegrid/api/treegrid_footerrowheight_config",
                    "treegrid/api/treegrid_grouptitletemplate_config",
                    "treegrid/api/treegrid_headerrowheight_config",
                    "treegrid/api/treegrid_headersort_config",
                    "treegrid/api/treegrid_height_config",
                    "treegrid/api/treegrid_htmlenable_config",
                    "treegrid/api/treegrid_leftsplit_config",
                    "treegrid/api/treegrid_resizable_config",
                    "treegrid/api/treegrid_rowcss_config",
                    "treegrid/api/treegrid_rowheight_config",
                    "treegrid/api/treegrid_selection_config",
                    "treegrid/api/treegrid_sortable_config",
                    "treegrid/api/treegrid_spans_config",
                    "treegrid/api/treegrid_splitat_config",
                    "treegrid/api/treegrid_tooltip_config",
                    "treegrid/api/treegrid_width_config",
                  ],
                },
                {
                  type: "category",
                  label: "Selection API",
                  items: [
                    {
                      type: "category",
                      label: "Methods",
                      items: [
                        "treegrid/api/selection/selection_afterselect_event",
                        "treegrid/api/selection/selection_afterunselect_event",
                        "treegrid/api/selection/selection_beforeselect_event",
                        "treegrid/api/selection/selection_beforeunselect_event",
                      ],
                    },

                    {
                      type: "category",
                      label: "Events",
                      items: [
                        "treegrid/api/selection/selection_disable_method",
                        "treegrid/api/selection/selection_enable_method",
                        "treegrid/api/selection/selection_getcell_method",
                        "treegrid/api/selection/selection_removecell_method",
                        "treegrid/api/selection/selection_setcell_method",
                      ],
                    },
                  ],
                },
              ],
            },
            "treegrid/events",
            "treegrid/initialization",
            "treegrid/customization",
            "treegrid/usage",
            "treegrid/usage_selection",
            "treegrid/migration",
            "treegrid/temp_api",
            "treegrid/data_loading",
            "treegrid/index",
            "treegrid/configuration",
          ],
        },
        // end TreeGrid

        //Window
        {
          type: "category",
          label: "Window",
          items: [
            "window/index",
            {
              type: "category",
              label: "API",
              items: [
                // "calendar/api/api_overview", //todo
                {
                  type: "category",
                  label: "Methods",
                  items: [
                    "window/api/window_attach_method",
                    "window/api/window_attachhtml_method",
                    "window/api/window_destructor_method",
                    "window/api/window_fullscreen_method",
                    "window/api/window_getcontainer_method",
                    "window/api/window_getposition_method",
                    "window/api/window_getsize_method",
                    "window/api/window_getwidget_method",
                    "window/api/window_hide_method",
                    "window/api/window_isvisible_method",
                    "window/api/window_paint_method",
                    "window/api/window_setfullscreen_method",
                    "window/api/window_setposition_method",
                    "window/api/window_setsize_method",
                    "window/api/window_show_method",
                  ],
                },
                {
                  type: "category",
                  label: "Events",
                  items: [
                    "window/api/window_afterhide_event",
                    "window/api/window_aftershow_event",
                    "window/api/window_beforehide_event",
                    "window/api/window_beforeshow_event",
                    "window/api/window_headerdoubleclick_event",
                    "window/api/window_move_event",
                    "window/api/window_resize_event",
                  ],
                },
                {
                  type: "category",
                  label: "Properties",
                  items: [
                    "window/api/window_closable_config",
                    "window/api/window_css_config",
                    "window/api/window_footer_config",
                    "window/api/window_header_config",
                    "window/api/window_height_config",
                    "window/api/window_html_config",
                    "window/api/window_left_config",
                    "window/api/window_minheight_config",
                    "window/api/window_minwidth_config",
                    "window/api/window_modal_config",
                    "window/api/window_movable_config",
                    "window/api/window_node_config",
                    "window/api/window_resizable_config",
                    "window/api/window_title_config",
                    "window/api/window_top_config",
                    "window/api/window_viewportoverflow_config",
                    "window/api/window_width_config",
                  ],
                },
              ],
            },
            "window/temp_api_windows",
            "window/how_to_start",
            "window/handling_events",
            "window/customization",
            "window/usage",
            "window/migration",
            "window/index",
            "window/configuration",
            "window/migration_1",
          ],
        },
        // end Window
      ],
    },
    //Helpers todo
    {
      type: "category",
      label: "Helpers",
      items: [
        {
          type: "category",
          label: "AJAX",
          items: [
            // "calendar/api/api_overview", //todo
            {
              type: "category",
              label: "Methods",
              items: [
                "window/api/window_attach_method",
                "window/api/window_attachhtml_method",
                "window/api/window_destructor_method",
                "window/api/window_fullscreen_method",
                "window/api/window_getcontainer_method",
                "window/api/window_getposition_method",
                "window/api/window_getsize_method",
                "window/api/window_getwidget_method",
                "window/api/window_hide_method",
                "window/api/window_isvisible_method",
                "window/api/window_paint_method",
                "window/api/window_setfullscreen_method",
                "window/api/window_setposition_method",
                "window/api/window_setsize_method",
                "window/api/window_show_method",
              ],
            },
          ],
        },
        {
          type: "doc",
          id: "helpers/await_redraw",
        },
        {
          type: "doc",
          id: "helpers/base_elements",
        },
        //todo разобраться с вложенностью
        {
          type: "doc",
          id: "css_manager/api/refs/css_manager",
        },

        {
          type: "category",
          label: "DataCollection API",
          items: [
            "helpers/data_collection",
            {
              type: "category",
              label: "Methods", //todo
              items: [
                "window/api/window_attach_method",
                "window/api/window_attachhtml_method",
                "window/api/window_destructor_method",
                "window/api/window_fullscreen_method",
                "window/api/window_getcontainer_method",
                "window/api/window_getposition_method",
                "window/api/window_getsize_method",
                "window/api/window_getwidget_method",
                "window/api/window_hide_method",
                "window/api/window_isvisible_method",
                "window/api/window_paint_method",
                "window/api/window_setfullscreen_method",
                "window/api/window_setposition_method",
                "window/api/window_setsize_method",
                "window/api/window_show_method",
              ],
            },
            {
              type: "category",
              label: "Events", //todo
              items: [
                "window/api/window_attach_method",
                "window/api/window_attachhtml_method",
                "window/api/window_destructor_method",
                "window/api/window_fullscreen_method",
                "window/api/window_getcontainer_method",
                "window/api/window_getposition_method",
                "window/api/window_getsize_method",
                "window/api/window_getwidget_method",
                "window/api/window_hide_method",
                "window/api/window_isvisible_method",
                "window/api/window_paint_method",
                "window/api/window_setfullscreen_method",
                "window/api/window_setposition_method",
                "window/api/window_setsize_method",
                "window/api/window_show_method",
              ],
            },
          ],
        },

        {
          type: "doc",
          id: "helpers/datadrivers",
        },

        //todo - всю вложенность сделать
        {
          type: "category",
          label: "DataProxy",
          items: [
            "helpers/data_collection",
            {
              type: "category",
              label: "Methods", //todo
              items: [
                "window/api/window_attach_method",
                "window/api/window_attachhtml_method",
                "window/api/window_destructor_method",
                "window/api/window_fullscreen_method",
                "window/api/window_getcontainer_method",
                "window/api/window_getposition_method",
                "window/api/window_getsize_method",
                "window/api/window_getwidget_method",
                "window/api/window_hide_method",
                "window/api/window_isvisible_method",
                "window/api/window_paint_method",
                "window/api/window_setfullscreen_method",
                "window/api/window_setposition_method",
                "window/api/window_setsize_method",
                "window/api/window_show_method",
              ],
            },
          ],
        },

        {
          type: "doc",
          id: "helpers/lazydataproxy",
        },

        {
          type: "doc",
          id: "helpers/resize_handler",
        },

        //todo - всю вложенность сделать
        {
          type: "category",
          label: "Selection Object API",
          items: [
            "helpers/selection",
            {
              type: "category",
              label: "Methods", //todo
              items: [
                "window/api/window_attach_method",
                "window/api/window_attachhtml_method",
                "window/api/window_destructor_method",
                "window/api/window_fullscreen_method",
                "window/api/window_getcontainer_method",
                "window/api/window_getposition_method",
                "window/api/window_getsize_method",
                "window/api/window_getwidget_method",
                "window/api/window_hide_method",
                "window/api/window_isvisible_method",
                "window/api/window_paint_method",
                "window/api/window_setfullscreen_method",
                "window/api/window_setposition_method",
                "window/api/window_setsize_method",
                "window/api/window_show_method",
              ],
            },
          ],
        },

        //todo - всю вложенность сделать
        {
          type: "category",
          label: "TreeCollection API",
          items: [
            "helpers/data_collection",
            {
              type: "category",
              label: "Methods", //todo
              items: [
                "window/api/window_attach_method",
                "window/api/window_attachhtml_method",
                "window/api/window_destructor_method",
                "window/api/window_fullscreen_method",
                "window/api/window_getcontainer_method",
                "window/api/window_getposition_method",
                "window/api/window_getsize_method",
                "window/api/window_getwidget_method",
                "window/api/window_hide_method",
                "window/api/window_isvisible_method",
                "window/api/window_paint_method",
                "window/api/window_setfullscreen_method",
                "window/api/window_setposition_method",
                "window/api/window_setsize_method",
                "window/api/window_show_method",
              ],
            },
          ],
        },

        //todo - всю вложенность сделать
        {
          type: "category",
          label: "Uploader Object API",
          items: [
            "helpers/data_collection",
            {
              type: "category",
              label: "Methods", //todo
              items: [
                "window/api/window_attach_method",
                "window/api/window_attachhtml_method",
                "window/api/window_destructor_method",
                "window/api/window_fullscreen_method",
                "window/api/window_getcontainer_method",
                "window/api/window_getposition_method",
                "window/api/window_getsize_method",
                "window/api/window_getwidget_method",
                "window/api/window_hide_method",
                "window/api/window_isvisible_method",
                "window/api/window_paint_method",
                "window/api/window_setfullscreen_method",
                "window/api/window_setposition_method",
                "window/api/window_setsize_method",
                "window/api/window_show_method",
              ],
            },
          ],
        },
      ],
    },

    // end Helpers

    // start Common features
    {
      type: "category",
      label: "Common features",
      items: [
        "guides/using_typescript",
        "guides/touch_support",
        // Localization todo,
        // ARIA todo,
        // Keyboard support todo
        // Стилизация todo
        // Frameworks support (Angular, React, Vue)
        // https://js.devexpress.com/DevExtreme/Guide/Common/TypeScript_Support/Reference_TypeScript_Definitions/
      ],
    },
    // end Common features

    {
      type: "category",
      label: "Creating app and binding widgets",
      items: [
        // With HTML and Layout,
        // With Frameworks
        {
          type: "category",
          label: "With Optimus",
          items: [
            "optimus_guides/index",
            "optimus_guides/how_to_start_optimus",
          ],
        },
      ],
    },
    {
      type: "doc",
      id: "whatsnew",
    },
  ],
};
